apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: ClusterIP
  selector:
    app: httpd  # Matches Deployment's pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678